[package]
authors = ["Bogdan Arabadzhi <barabadzhi@iba.by>"]
name = "time-api"
version = "0.1.0"

[dependencies]
chrono = "0.4.0"
rocket = "0.3.2"
rocket_codegen = "0.3.2"
rocket_contrib = "0.3.2"
serde = "1.0.11"
serde_derive = "1.0.11"
